// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// permutation_ssq_kernel_cpp
Rcpp::NumericVector permutation_ssq_kernel_cpp(const arma::mat& DD, const arma::mat& DR, const Rcpp::List& groups, const int n_perm);
RcppExport SEXP _HDANOVA_permutation_ssq_kernel_cpp(SEXP DDSEXP, SEXP DRSEXP, SEXP groupsSEXP, SEXP n_permSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type DD(DDSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type DR(DRSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< const int >::type n_perm(n_permSEXP);
    rcpp_result_gen = Rcpp::wrap(permutation_ssq_kernel_cpp(DD, DR, groups, n_perm));
    return rcpp_result_gen;
END_RCPP
}
// rotation_ssq_kernel_cpp
Rcpp::NumericVector rotation_ssq_kernel_cpp(const arma::mat& DD, const arma::mat& DR, const Rcpp::List& groups, const int n_rot);
RcppExport SEXP _HDANOVA_rotation_ssq_kernel_cpp(SEXP DDSEXP, SEXP DRSEXP, SEXP groupsSEXP, SEXP n_rotSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type DD(DDSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type DR(DRSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< const int >::type n_rot(n_rotSEXP);
    rcpp_result_gen = Rcpp::wrap(rotation_ssq_kernel_cpp(DD, DR, groups, n_rot));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_HDANOVA_permutation_ssq_kernel_cpp", (DL_FUNC) &_HDANOVA_permutation_ssq_kernel_cpp, 4},
    {"_HDANOVA_rotation_ssq_kernel_cpp", (DL_FUNC) &_HDANOVA_rotation_ssq_kernel_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_HDANOVA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
