---
title: "Caldana"
author: "Liland"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(multiblock)
library(HDANOVA)
```

## Caldana data from R app

```{r cars}
load("development/examples/Caldana/caldana_from_app.RData")
nam <- c('Alanine', 'Valine', 'Leucine', 'Isoleucine', 'Proline', 'Serine', 'Threonine', 'beta-alanine', 'Hydroxyproline', 'GABA', 'Aspartate', 'Asparagine', 'Methionine', 'O-acetyl-serine', 'Glutamate', 'Phenylalanine', 'Ornithine', 'Glutamine', 'Lysine', 'Tyrosine', 'Threonic-acid', 'Citrulline-Arginine', 'Pyruvic-acid', 'Citric-acid', 'Succinic-acid', 'Fumaric-acid', 'Malic-acid', 'Lactic-acid', 'Glycolic-acid', 'Benzoic-acid', 'Maleic-acid', 'Nicotinic-acid', 'Itaconic-acid', 'Citramalate', '4-hydroxy-benzoic-acid', 'Dehydroascorbic-acid-dimer', 'Gluconic-acid', 'Dehydroascorbic-acid', 'Ascorbic-acid', '4-Hydroxycinnamic-acid', 'Similar-to-Adenine', 'Shikimate', 'Erythritol', 'Arabinose', 'Arabitol', 'Fucose', 'Fructose', 'Mannitol', 'Galactose', 'Glucose', 'Sucrose', 'Maltose', 'Trehalose', 'Galactinol', 'myo-inositol', 'Uracil', 'Putrescine', 'Ethanolamine', 'Glycerol', 'Indole-3-acetonitrile', 'Sinapic-acid', 'Palmitic-acid', 'Octadecanoic-acid', 'Docosanoic-acid', 'Tetracosanoic-acid', 'Hexacosanoic-acid', 'Octacosanoic-acid')
```

## Estimate all

```{r}
mod <- asca(Y~light*time, caldana, add_error = FALSE, coding = "sum")
#modM <- multiblock::asca(Y~light*time, caldana)
expl <- attr(mod$scores$light, "explvar")
expl
mod$explvar
```

## Combine level and light:time

```{r}
pc <- multiblock::pca(mod$LS$light + mod$LS$`light:time`, ncomp=10)
rownames(pc$loadings) <-  1:67
mod2 <- mod
mod2$scores[[1]] <- pc$scores
mod2$loadings[[1]] <- pc$loadings
mod2$projected[[1]] <- mod2$residuals %*% pc$loadings
mod2$effects[[1]] <- mod2$effects$`light:time`

par(mfrow=c(1,1), mar=c(4,4,1,1))
scoreplot(mod2)

#png("Caldana_ASCA.png", 1000,1200, pointsize = 36)
pdf("Caldana_ASCA.pdf", 15,18, pointsize = 36)
par(mfrow=c(3,1), mar=c(2,4,2,1), mgp = c(2.5, 1, 0))
barplot(t(pc$loadings[,1:2]), beside=TRUE, ylab="loading value", main=paste0("light + time:light (",round(sum(mod$explvar[2:3])*100,2),"%)"),
        legend.text = c(paste0("Component 1 (",round(pc$explvar[1],1),"%)"), paste0("Component 2 (",round(pc$explvar[2],1),"%)")), names.arg = rep("",67), args.legend = c("x"="topright"), lwd=2)
graphics::box()
text(82,0.65, "O-acetyl-serine", cex=0.9, pos=2)
lines(c(43,50),c(0.45,0.58), lwd=3)
text(141,-0.5, "Fructose", cex=0.9, pos=2)
lines(c(131,138),c(-0.44,-0.31), lwd=3)
text(171,-0.4, "Glucose", cex=0.9, pos=2)
lines(c(155,150),c(-0.32,-0.22), lwd=3)

par(mar=c(4,4,0,1))
means <- tapply(mod2$scores[[1]][,1], mod2$effects$`light:time`, mean)
x <- c(0,5,10,20,40,80,160)
plot(1:7, means[seq(1,28, 4)], type="l", ylab = paste0("Score 1 (",round(pc$explvar[1],1),"%)"), xlab = "time", ylim = c(min(means),max(means)), axes = FALSE, lwd=4, panel.first = {abline(h=0, lty=2, col="gray")})
axis(1, 1:7, x)
axis(2)
graphics::box()
lines(1:7, means[seq(2,28, 4)], type="l", col=2, lty=2, lwd=4)
lines(1:7, means[seq(3,28, 4)], type="l", col=3, lty=3, lwd=4)
lines(1:7, means[seq(4,28, 4)], type="l", col=4, lty=4, lwd=4)
legend("bottomleft", legend=c("Dark","Low light","Light", "High light"),
       col=1:4, lty=1:4, lwd=rep(4,4))

means <- tapply(mod2$scores[[1]][,2], mod2$effects$`light:time`, mean)
x <- c(0,5,10,20,40,80,160)
plot(1:7, means[seq(1,28, 4)], type="l", ylab = paste0("Score 2 (",round(pc$explvar[2],1),"%)"), xlab = "time", ylim = c(min(means),max(means)), axes = FALSE, lwd=4)
axis(1, 1:7, x)
axis(2)
graphics::box()
lines(1:7, means[seq(2,28, 4)], type="l", col=2, lty=2, lwd=4)
lines(1:7, means[seq(3,28, 4)], type="l", col=3, lty=3, lwd=4)
lines(1:7, means[seq(4,28, 4)], type="l", col=4, lty=4, lwd=4)
#legend("top", legend=c("Dark","Low light","Light", "High light"),
#       col=1:4, lty=1:4, lwd=rep(4,4))
dev.off()
```

# APCA

```{r}
mod <- apca(Y~light*time, caldana)
#modM <- multiblock::asca(Y~light*time, caldana)
expl <- attr(mod$scores$light, "explvar")
expl
mod$explvar
```

## Combine time and light:time

```{r}
pc <- multiblock::pca(mod$LS$light + mod$LS$`light:time`, ncomp=10)
rownames(pc$loadings) <-  1:67
mod2 <- mod
mod2$scores[[1]] <- pc$scores
mod2$loadings[[1]] <- pc$loadings
mod2$projected[[1]] <- mod2$residuals %*% pc$loadings
mod2$effects[[1]] <- mod2$effects$`light:time`

par(mfrow=c(1,1), mar=c(4,4,1,1))
scoreplot(mod2)

#png("Caldana_APCA.png", 1000,1200, pointsize = 36)
pdf("Caldana_APCA.pdf", 15,18, pointsize = 36)
par(mfrow=c(3,1), mar=c(2,4,2,1), mgp = c(2.5, 1, 0))
barplot(t(pc$loadings[,1:2]), beside=TRUE, ylab="loading value", main=paste0("light + time:light (",round(sum(mod$explvar[2:3])*100,2),"%)"),
        legend.text = c(paste0("Component 1 (",round(pc$explvar[1],1),"%)"), paste0("Component 2 (",round(pc$explvar[2],1),"%)")), names.arg = rep("",67), args.legend = c("x"="bottomleft"), lwd=2)
graphics::box()
text(140,-0.55, "Fructose", cex=0.9, pos=2)
lines(c(137,130),c(-0.42,-0.52), lwd=3)
text(110,-0.48, "Maleic acid", cex=0.9, pos=2)
lines(c(94,101),c(-0.34,-0.44), lwd=3)
text(190,-0.38, "Docosanoic", cex=0.9, pos=2)
text(185,-0.425, "acid", cex=0.9, pos=2)
lines(c(189,182),c(-0.24,-0.34), lwd=3)
text(210,-0.505, "Tetracosanoic", cex=0.9, pos=2)
text(205,-0.55, "acid", cex=0.9, pos=2)
lines(c(195,200),c(-0.37,-0.47), lwd=3)

par(mar=c(4,4,0,1))
means <- tapply(mod2$scores[[1]][,1], mod2$effects$`light:time`, mean)
x <- c(0,5,10,20,40,80,160)
plot(1:7, means[seq(1,28, 4)], type="l", ylab = paste0("Score 1 (",round(pc$explvar[1],1),"%)"), xlab = "time", ylim = c(min(means),max(means)), axes = FALSE, lwd=4, panel.first = {abline(h=0, lty=2, col="gray")})
axis(1, 1:7, x)
axis(2)
graphics::box()
lines(1:7, means[seq(2,28, 4)], type="l", col=2, lty=2, lwd=4)
lines(1:7, means[seq(3,28, 4)], type="l", col=3, lty=3, lwd=4)
lines(1:7, means[seq(4,28, 4)], type="l", col=4, lty=4, lwd=4)
legend("bottomleft", legend=c("Dark","Low light","Light", "High light"),
       col=1:4, lty=1:4, lwd=rep(4,4))

means <- tapply(mod2$scores[[1]][,2], mod2$effects$`light:time`, mean)
x <- c(0,5,10,20,40,80,160)
plot(1:7, means[seq(1,28, 4)], type="l", ylab = paste0("Score 2 (",round(pc$explvar[2],1),"%)"), xlab = "time", ylim = c(min(means),max(means)), axes = FALSE, lwd=4)
axis(1, 1:7, x)
axis(2)
graphics::box()
lines(1:7, means[seq(2,28, 4)], type="l", col=2, lty=2, lwd=4)
lines(1:7, means[seq(3,28, 4)], type="l", col=3, lty=3, lwd=4)
lines(1:7, means[seq(4,28, 4)], type="l", col=4, lty=4, lwd=4)
#legend("bottomright", legend=c("Dark","Low light","Light", "High light"),
#       col=1:4, lty=1:4, lwd=rep(4,4))
dev.off()
```

## PRC

```{r}
library(vegan)
level <- caldana$light
time <- caldana$time
prc.cal <- prc(caldana$Y, level, time)

png("Caldana_PRC.png", 800,1000, pointsize = 36)
par(mfrow=c(2,1), mar=c(4,4,1,1))
plot(prc.cal, species = FALSE, axis = 1, lwd = 4)
dev.flush()
plot(prc.cal, species = FALSE, axis = 2, lwd = 4, legpos = "bottomright")
plot(0)
dev.off()

# summary(prc.cal)
prc.cal
```

```{r}
plot(prc.cal, species = FALSE, axis = 2, lwd = 4, legpos = "bottomright")
x <- summary(prc.cal, axis = 2, scaling = "symmetric", correlation = FALSE)
par(mfrow=c(1,1))
matplot(colnames(coef(x)), t(coef(x)), lty=2:4, col= 2:4, type="l", lwd=4, xlab="time", ylab="effect")
lines(c(0,160), c(0,0), lwd=4)
matplot(colnames(coef(x)), t(coef(x)), lty=2:4, col= 2:4, type="l", lwd=4, add=TRUE)
```

```{r}
cca_expl <- prc.cal$CCA$eig/prc.cal$CCA$tot.chi*100
#png("Caldana_PRC.png", 1000,1200, pointsize = 36)
pdf("Caldana_PRC.pdf", 15,18, pointsize = 36)
par(mfrow=c(3,1), mar=c(2,4,2,1), mgp = c(2.5, 1, 0))
scores(prc.cal)$species
#barplot(t(prc.cal$CCA$v[,1:2]), beside=TRUE, ylab="Correlation", main=paste0("light +
barplot(t(scores(prc.cal)$species[,1:2]), beside=TRUE, ylab="loading value", main=paste0("light + time:light (",round(prc.cal$CCA$tot.chi/prc.cal$tot.chi*100,2),"%)"),
        legend.text = c(paste0("Component 1 (",round(cca_expl[1],1),"%)"), paste0("Component 2 (",round(cca_expl[2],1),"%)")), names.arg = rep("",67), args.legend = c("x"="top"), lwd=2)
graphics::box()
text(40,0.9, "O-acetyl-serine", cex=0.9, pos=2)
lines(c(32,39),c(0.82,0.72), lwd=3)
text(140,0.58, "Fructose", cex=0.9, pos=2)
lines(c(133,138),c(0.52,0.42), lwd=3)
text(175,0.75, "Glucose", cex=0.9, pos=2)
lines(c(150,155),c(0.57,0.69), lwd=3)

par(mar=c(4,4,0,1))
x <- summary(prc.cal, axis = 1, scaling = "symmetric", correlation = FALSE)
matplot(1:7, t(coef(x)), lty=2:4, col= 2:4, type="l", lwd=4, xlab="time", ylab=paste0("Score 1 (",round(cca_expl[1],1),"%)"), axes=FALSE)
lines(c(0,160), c(0,0), lwd=4)
matplot(1:7, t(coef(x)), lty=2:4, col= 2:4, type="l", lwd=4, add=TRUE, axes=FALSE)
legend("topleft", legend=c("Dark","Low light","Light", "High light"),
       col=1:4, lty=1:4, lwd=rep(4,4))
axis(1, 1:7, colnames(coef(x)))
axis(2)
graphics::box()

x <- summary(prc.cal, axis = 2, scaling = "symmetric", correlation = FALSE)
matplot(1:7, t(coef(x)), lty=2:4, col= 2:4, type="l", lwd=4, xlab="time", ylab=paste0("Score 2 (",round(cca_expl[2],1),"%)"), axes=FALSE)
lines(c(0,160), c(0,0), lwd=4)
matplot(1:7, t(coef(x)), lty=2:4, col= 2:4, type="l", lwd=4, add=TRUE, axes=FALSE)
axis(1, 1:7, colnames(coef(x)))
axis(2)
graphics::box()
dev.off()
```

