# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.permutation_ssq_kernel_cpp <- function(DD, DR, groups, n_perm) {
    .Call(`_HDANOVA_permutation_ssq_kernel_cpp`, DD, DR, groups, n_perm)
}

.rotation_ssq_kernel_cpp <- function(DD, DR, groups, n_rot) {
    .Call(`_HDANOVA_rotation_ssq_kernel_cpp`, DD, DR, groups, n_rot)
}

